language: python
python:
- "3.7"
# setup environment
env:
- DJANGO_VERSION=1.11.2
# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- python manage.py test 
